### ISSUE TITLE
install fails on a fresh conda installation

### ISSUE THREAD

**Issue by epifanio** [conda-forge/gdal-feedstock#112]
Installer used:  Anaconda3-4.1.1-Windows-x86_64

log:

```
The following specifications were found to be in conflict: - gdal -> jpeg 9* - gdal -> python 2.6*|2.7*|3.3*|3.4* Use "conda info <package>" to see the dependencies for each package.
```

**Comment by gillins** [comment]
Try running `conda update --all` first, and let us know if that fixes it. Which version of Python are you using?

**Comment by epifanio** [comment]
Hi, I tryied an ```update --all``` not the logs says:

```
The following specifications were found in conflict:
  - gdal
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by epifanio** [comment]
This is with latyest conda installer for python 3.5.2

**Comment by ocefpaf** [comment]
Windows and Python 3.5 is problematic because of `jpeg 8*` (used on `defaults`) and `jpeg 9*` used on `conda-forge`. Anything that requires `jpeg 8*` from `defaults`, like `qt` (via `matplotlib` for example) will result in that conflict.

The solution is either `defaults` upgrade to the less buggy `jpeg 9*` or if `conda-forge` start building `qt`. The problem to build `qt` on `conda-forge` is that we are time limited by the CI... So we are between a rock and a hard place here.

**Comment by epifanio** [comment]
Oh! I see the issue. 
I wonder what jpeg will be used on [qttesting](https://anaconda.org/qttesting channel) channel. Perhaps they are using the new jpeg?

**Comment by ocefpaf** [comment]
> I wonder what jpeg will be used on [qttesting](https://anaconda.org/qttesting channel) channel. Perhaps they are using the new jpeg?

No idea. Either way this problem is  a headache for Windows users to move to `Python 3.5` and we need to find a solution ASAP.

**Comment by valgur** [comment]
Maybe a bit off topic, but I think the GDAL package or conda-forge would benefit from switching to [libjpeg-turbo](http://libjpeg-turbo.virtualgl.org/) in place of libjpeg. It is fully compatible with it up to version 8.

The main reason I'm suggesting this is because the current libjpeg maintainer keeps pushing out major release versions which are not backwards-compatible in terms of C ABI, which is the reason why we can't use version 8 and 9 interchangeably. This fact would not be a huge problem by itself, but the reason the new major versions keep getting released is to add new functionality which no-one is really asking for, is non-standard and is unsupported by other software.

Frankly, the current maintainer comes across as not-quite-sane to me. See http://hardwarebug.org/2009/08/04/ijg-is-back/, http://hardwarebug.org/2010/02/01/ijg-swings-again-and-misses/, http://hardwarebug.org/2014/05/25/church-of-jpeg/. He seems to be abusing libjpeg's status of being the de facto reference implementation to add his personal pet projects to it without a thought for the stability of downstream software, such as this project.

For these reasons, libjpeg-turbo has [decided to break its compatibility](http://www.libjpeg-turbo.org/About/Jpeg-9) to libjpeg starting from libjpeg version 9.

Last but not least, libjpeg-turbo should be 2-6x as fast and is used in some significant projects such as Google Chrome and Mozilla Firefox, so it should be thoroughly vetted by now.

**Comment by ocefpaf** [comment]
@valgur my Linux distro uses `libjpeg-turbo` and I have been thinking what would be the advantages of that for a while. Thanks for the links, they really helped.

We can definitely experiment with that. I guess that the first step would be to submit a recipe for `libjpeg-turbo` to [`staged-recipes`](https://github.com/conda-forge/staged-recipes). Is that something you would like to try?

**Comment by valgur** [comment]
Sure, I'll give it a try. I haven't created one before but I think I'll enjoy getting to know conda-forge a bit better.

**Comment by ocefpaf** [comment]
> Sure, I'll give it a try. I haven't created one before but I think I'll enjoy getting to know conda-forge a bit better.

Feel free to ping me for help.

**Comment by davidh-ssec** [comment]
Based on previous posts it sounds like this issue only affects python 3.5, is that true? I'm using python 3.4 and I'm seeing this, is there a work around. My issue is using gdal and qt (both pyqt and matplotlib, I think).

**Comment by valgur** [comment]
@davidh-ssec It seems to be the case. I had to downgrade my environment to Python 3.4 to be able to use GDAL and libraries dependent on Qt simultaneously.

**Comment by ocefpaf** [comment]
> @davidh-ssec It seems to be the case. I had to downgrade my environment to Python 3.4 to be able to use GDAL and libraries dependent on Qt simultaneously.

That is correct. We are discussing how to get a qt package in `conda-forge` to fix that for good. Because we cannot build `Qt` on AppVeyor we need to upload a pre-built binary. Please show your support to https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5 to help this move forward.

**Comment by davidh-ssec** [comment]
@valgur are there specific versions of Qt and GDAL that you had to use? Maybe one of my other dependencies was limiting the version of gdal/qt.

@ocefpaf Thanks.

**Comment by valgur** [comment]
@davidh-ssec Ah, yes, I think I actually needed GDAL >= 2. Sorry, it has been a few weeks since then. GDAL 1.11 probably works, as you said.

**Comment by valgur** [comment]
@ocefpaf I created a `libjpeg-turbo` recipe in https://github.com/valgur/staged-recipes/tree/libjpeg-turbo/recipes/libjpeg-turbo
and a `jpeg` metapackage depending on it at https://github.com/valgur/staged-recipes/tree/libjpeg-turbo/recipes/jpeg.

My `libjpeg-turbo` package currently only supports Linux systems. Adding Windows support should be straightforward but I'm lacking the time for that today. 

A problem with the `libjpeg-turbo` package is that it is a drop-in replacement for `libjpeg` and as such includes library files with the exact names, causing a conflict. I don't currently have any good ideas how to resolve this. One approach, which is used in Ubuntu, is to make `libjpeg` a metapackage that depends on `libjpeg-turbo`. I created something similar above. My `jpeg` metapackage has a version of the form `{{libjpeg_version}}_turbo_{{turbo_version}}`. That way it should be possible for packages that have a dependency version set like `jpeg 8*` to use the `libjpeg-turbo` variant without any extra work. Ideally, I would like to follow the lead of Ubuntu and other distros that simply substitute the exact `libjpeg` version (e.g. 8c) with its turbo equivalent, but this would need discussion and cooperation at some greater level of the project.

Does it look reasonable so far? I'm eager to see if building `libtiff` or `gdal` on top of the `libjpeg-turbo` package works. Would you like to experiment with that?

**Comment by ocefpaf** [comment]
> @ocefpaf I created a `libjpeg-turbo` recipe in https://github.com/valgur/staged-recipes/tree/libjpeg-turbo/recipes/libjpeg-turbo

Nice! Send a PR to staged recipes, it is OK to skip the Windows builds for now, so we can build and test. If everything is OK we can merge and get `libjpeg-turbo` in the channel. That does not mean we will be able to use it immediately, but we will be able to test with it, 

> and a `jpeg` metapackage depending on it at https://github.com/valgur/staged-recipes/tree/libjpeg-turbo/recipes/jpeg.

To be honest I dislike complexities. I'd prefer that, if we make the move to `libjpeg-turbo`, we move everything to it. However, a metapackage may be in order and we will probably need to ping others later on when the time comes. I would not worry about that for now as we still need a discussion on which `jpeg` conda-forge should use by default and that won't happen here (in issues). More on that later.

> My `libjpeg-turbo` package currently only supports Linux systems. Adding Windows support should be straightforward but I'm lacking the time for that today. 

:+1: 

> A problem with the `libjpeg-turbo` package is that it is a drop-in replacement for `libjpeg` and as such includes library files with the exact names, causing a conflict. I don't currently have any good ideas how to resolve this. One approach, which is used in Ubuntu, is to make `libjpeg` a metapackage that depends on `libjpeg-turbo`. I created something similar above. My `jpeg` metapackage has a version of the form `{{libjpeg_version}}_turbo_{{turbo_version}}`. That way it should be possible for packages that have a dependency version set like `jpeg 8*` to use the `libjpeg-turbo` variant without any extra work. Ideally, I would like to follow the lead of Ubuntu and other distros that simply substitute the exact `libjpeg` version (e.g. 8c) with its turbo equivalent, but this would need discussion and cooperation at some greater level of the project.

We will need to open that for discussion. Maybe even write a [conda-forge enhancement proposal](https://github.com/conda-forge/conda-forge-enhancement-proposals). Before we make the move. That is why I would like to get `libjpeg-turbo` as a feedstock, so we can start testing and make a stronger case later on.

> Does it look reasonable so far?

Yes.

> I'm eager to see if building `libtiff` or `gdal` on top of the `libjpeg-turbo` package works. Would you like to experiment with that?

Me too :smile:

**Comment by valgur** [comment]
Ok, I created [the pull request](https://github.com/conda-forge/staged-recipes/issues/1738). Made the build work on Windows as well.

**Comment by ocefpaf** [comment]
Closing this because the `libjpeg-turbo` should be in another discussion and the original problem can be solved by using all `conda-forge` packages that are consistent with `jpeg 9*` and giving up any packages from `defaults` that uses `jpeg 8*`. That is a limitation for those using `Qt`, `matplotlib`, etc with `conda-forge`;s `gdal`, but we will have to deal with that limitation until `conda-forge` can build `Qt` on all platforms.

Anyone the latter issue resolved please show your support to https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5
