### ISSUE TITLE
proj.4 -> proj4 gdal 1.11.4

### ISSUE THREAD

**Issue by bucricket** [conda-forge/gdal-feedstock#146]
I'm wondering if you can fix the the gdal 1.11.4 version to reflect the proj.4 -> proj4 naming issue. I'm trying to use raster 0.32.0 which depends on 1.11.4 and I get the following decency error when trying to use rasterio to build landsat-util 0.13.1

rasterio 0.32.0* -> gdal 1.11.4 -> proj.4

**Comment by ocefpaf** [comment]
The renaming happened last year. See https://github.com/conda-forge/gdal-feedstock/pull/125/commits/984b2c8cdd3bab7fb3d2b6985adb743b49dcae98

My guess is that some other dependency is requiring `proj.4` (deprecated) instead of `proj4` (current).

.If you can point me to your software that is causing that error I can try to investigate this, but the problem is not `gdal`.

**Comment by bucricket** [comment]
Yeah its in the 1.11.4 feedstock see the yaml file below.




# This file created by conda-build 1.20.3
# meta.yaml template originally from:
# /recipe_root, last modified Fri Jun  3 17:53:48 2016
# ------------------------------------------------

package:
    name: gdal
    version: 1.11.4
source:
    fn: gdal-1.11.4.tar.gz
    md5: e9a966f0f5a88c43da47faf78a865952
    patches:
        - install_scripts.patch
    url: http://download.osgeo.org/gdal/1.11.4/gdal-1.11.4.tar.gz
build:
    features: ''
    number: '10'
requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - hdf4
        - hdf5 1.8.17*
        - geos
        - proj.4
        - xerces-c
        - libnetcdf 4.4*
        - krb5
        - libpng 1.6*
        - openjpeg
        - libtiff 4.0.6
        - jpeg 9*
        - curl
        - expat
        - zlib 1.2*
        - postgresql
        - jasper
        - giflib
        - json-c
        - freexl
        - libspatialite
    run:
        - python
        - numpy x.x
        - hdf4
        - hdf5 1.8.17*
        - geos
        - proj.4
        - xerces-c
        - libnetcdf 4.4*
        - krb5
        - libpng 1.6*
        - openjpeg
        - libtiff 4.0.6
        - jpeg 9*
        - curl
        - expat
        - zlib 1.2*
        - postgresql
        - jasper
        - giflib
        - json-c
        - freexl
        - libspatialite
test:
    commands:
        - ogrinfo sites.shp
        - gdal_grid --version
        - gdal_rasterize --version
        - gdal_translate --version
        - gdaladdo --version
        - gdalenhance --version
        - gdalwarp --version
        - gdalinfo --formats
        - conda inspect linkages -n _test gdal
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
        - cropped.cub
    imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)
extra:
    recipe-maintainers:
        - ocefpaf
        - kmuehlbauer
        - gillins

**Comment by ocefpaf** [comment]
That is because we have `1.11.5` in the `gdal` series. It should work for you.

**Comment by bucricket** [comment]
HI,

I’m still trying to get the hang of conda build and anaconda cloud so bear with me.  I’m trying to build a package (landsat-util) that depends on rasterio 0.32.0.  A couple questions:

1. I assume that in the yaml depencies that it chooses the latest build of the version.  Because build 2 of gdal 1.11.5 still has the proj.4 name.  Is that correct?
2. If I really can’t use 1.11.4 I assume it is deprecated, shouldn’t there be some mechanism to indicate that in the build process?

3. There is no build of rasterio version 0.32.0 that depends on gdal 1.11.5 all builds depend on gdal 1.11.4,  shouldn’t there be a build that uses gdal 1.11.5 if nothing is different from 1.11.4.

Thanks for your help!

Mitch

**Comment by ocefpaf** [comment]
> I’m still trying to get the hang of conda build and anaconda cloud so bear with me. 

No problem.

>   I’m trying to build a package (landsat-util) that depends on rasterio 0.32.0.

Is that package on GitHub or somewhere online?

> 1. I assume that in the yaml depencies that it chooses the latest build of the version.  Because build 2 of gdal 1.11.5 still has the proj.4 name.  Is that correct?

You can pin to `gdal 1.11.5`.

> 2. If I really can’t use 1.11.4 I assume it is deprecated, shouldn’t there be some mechanism to indicate that in the build process?

There is no need as long as the rest of the stack "knows" that you should get a higher version.

> 3. There is no build of rasterio version 0.32.0 that depends on gdal 1.11.5 all builds depend on gdal 1.11.4,  shouldn’t there be a build that uses gdal 1.11.5 if nothing is different from 1.11.4.

That is probably the problem here. The last version `rasterio` was built against `gdal 1.11.x`, in theory that should get `1.11.5` but it is not. Probably because that version of `rasterio` is pinned to software that is incompatible with `gdal 1.11.5`

It is complicated for me to issue a re-build of `rasterio` just to fix that without ensuring that we will have the right stack to build `landsat-util`. If you can point me to `landsat-util` code and recipe I can try to fix that for you.

**Comment by bucricket** [comment]
Hi,

Thanks for the reply.   Landsat-util has no feedstock right now but here is the GitHub site if that helps.

https://github.com/developmentseed/landsat-util.git <https://github.com/developmentseed/landsat-util.git>

PS what do you mean by pin?

Mitch

**Comment by ocefpaf** [comment]
> Landsat-util has no feedstock right now but here is the GitHub site if that helps.

I am creating one. It is pending the merge of:

https://github.com/conda-forge/scikit-image-feedstock/pull/4

and 

https://github.com/conda-forge/gdal-feedstock/pull/147

> What do you mean by pin?

Pin to a specific version. Like the requirement for `landsat-util`. Although that one is probably too strict and we should check what can be relaxed. See https://github.com/developmentseed/landsat-util/issues/223

I tested locally with unpinned versions of almost everything but I kept `rasterio <1` and `gdal 1.11.*`.
I got a successful build but I am getting a few test failures (9 out of 63). See  https://gist.github.com/ocefpaf/6fa7fba5ecbc6e2c90ce70a269c39c73

Some of those are could probably by just updating the test values, others I am not sure...
You advice on that version can be relaxed and what version should be pinned is welcomed because I am preparing a PR to add `geocoder`, `homura`, `landsat-util`, `polyline`, `ratelim`, `requests_futures`, and `usgs` to `conda-forge` and it would be nice to add the latest version instead of those strictly pinned  in https://github.com/developmentseed/landsat-util/blob/develop/requirements.txt

**Comment by bucricket** [comment]
Awesome!  You can look at my channel : bucricket.  I built Landsat-util on OS X-64 but I was struggling on linux.

Thanks
Mitch

**Comment by bucricket** [comment]
Putting Landsat-util on conda-forge will be great also because it is a very popular tool.  Even Amazon promotes it.

https://aws.amazon.com/blogs/aws/start-using-landsat-on-aws/ <https://aws.amazon.com/blogs/aws/start-using-landsat-on-aws/>

Mitch
