### ISSUE TITLE
GDAL looking for old version of libgeos

### ISSUE THREAD

**Issue by Auerilas** [conda-forge/gdal-feedstock#151]
Hi,
I recently switched to the conda forge channel and updated all my packages. It seems as though all the spatial libraries (geopandas, fiona, etc), which depend on gdal, were looking for an older version of libgeos than existed. 

When attempting to import gdal, I would get this error:
`ImportError: libgeos-3.5.0.so: cannot open shared object file: No such file or directory`

conda-forge had installed libgeos-3.5.1, so I resolved this issue by forcing a downgrade of geos:
`conda install geos=3.5.0`

and all works now. Is there any way to update gdal to search for the newest version of geos?

**Comment by ocefpaf** [comment]
`gdal` is pinned to `geos 3.5.*` and not geos `3.5.0`. See https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/meta.yaml#L40

That means the latest `gdal` build was built against `geos 3.5.1`. I am guessing you may have a bad mix of `defaults` and `conda-forge` packages. (See http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels)

```shell
conda create --yes -n GDAL python=3.6 geopandas 
source activate GDAL
> python -c "import geopandas; print(geopandas.__version__)"
0.2.1
> python -c "import gdal; print(gdal.__file__)"   
/home/filipe/miniconda3/envs/GDAL/lib/python3.6/site-packages/gdal.py
```

We could ping `gdal` down to the micro version but you should not get things compiled against `geos 3.5.0` unless you have `defaults` with higher priority than `conda-forge`.

**Comment by Auerilas** [comment]
Hi,

I checked my priority settings:

```
auerilas@Nate ~ $ cat .condarc
channels:
  - conda-forge
  - defaults
```

which look OK per the link above. To test, I removed gdal, fiona, shapely, geos, and all spatial packages and reinstalled.

```
auerilas@Nate ~ $ conda install fiona
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/auerilas/anaconda3:

The following NEW packages will be INSTALLED:

    fiona:   1.7.5-np112py35_0 conda-forge
    gdal:    2.1.0-py35_0                 
    geos:    3.5.1-1           conda-forge
    libgdal: 2.1.0-0                      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

```

and I'm getting the same error about geos 3.5.0.

If I'm reading the install correctly, is conda not using conda-forge to install gdal and libgdal, while using conda-forge for geos and fiona?

**Comment by ocefpaf** [comment]
The fact that you are getting `libgdal` indicates that somehow `defaults` is getting some priority. Did you try in a fresh env like in my example above. Note that https://github.com/conda-forge/conda-forge.github.io/issues/367 won't help you here because `conda` will wiggle its way out of the pin by installing `defaults` version.

**Comment by Auerilas** [comment]
The new environment did work. Is there any way to force conda to install the conda-forge version of a package? I'm not sure why defaults gets priority on some packages. For example, when I created the new environment, scipy and numpy were installed from the default channel. In my root environment, though, both packages come from conda-forge.

**Comment by Auerilas** [comment]
I ask because this:

```
auerilas@Nate ~ $ conda install -c conda-forge gdal
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/auerilas/anaconda3:

The following NEW packages will be INSTALLED:

    gdal: 2.1.0-py35_0
```

appeared not to force the install from conda-forge.

**Comment by ocefpaf** [comment]
Are you using Anaconda and installing in the root env? That may be troublesome b/c conda is trying to optimize for all the pre-installed packages. There is not much we can do besides forcing like you did above,  but that may lead to broken envs. ideally we should always work with envs and not the root env to avoid that.

**Comment by Auerilas** [comment]
Hmm. ok. I'll look into using an environment, but I tend to use the same packages for everything so maybe one environment that contains all my packages might be all I need.

Other than that, I'll keep using my forced downgrade as long as it works. Thanks for the help!

**Comment by gboeing** [comment]
@ocefpaf I'm experiencing the same issue when I try to test OSMnx with Travis CI today. I'm testing it with Python 2.7, 3.5, and 3.6 in a virtual environment and with conda-forge at the top of my channel URLs. The [Python 3.6](https://travis-ci.org/gboeing/osmnx/jobs/245602534) test works fine, and it correctly installs libgdal (v2.2.0-0) from conda-forge. However, the [Python 2.7](https://travis-ci.org/gboeing/osmnx/jobs/245602532) and [Python 3.5](https://travis-ci.org/gboeing/osmnx/jobs/245602533) tests fail. If you look at the logs, you see that for 2.7 and 3.5 conda installs libgdal (v2.1.0-0) from defaults instead of conda-forge. In all three cases, geos v3.5.1-1 from conda-forge is installed. However, for py2.7 and py3.5, I get the following error:

```
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_osmnx.py _____________________
ImportError while importing test module '/home/travis/build/gboeing/osmnx/tests/test_osmnx.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_osmnx.py:13: in <module>
    import osmnx as ox, logging as lg
osmnx/__init__.py:8: in <module>
    from .buildings import *
osmnx/buildings.py:9: in <module>
    import geopandas as gpd
../../../miniconda/envs/TESTENV/lib/python3.5/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
../../../miniconda/envs/TESTENV/lib/python3.5/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
../../../miniconda/envs/TESTENV/lib/python3.5/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../../miniconda/envs/TESTENV/lib/python3.5/site-packages/fiona/collection.py:7: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: libgeos-3.5.0.so: cannot open shared object file: No such file or directory
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.91 seconds ============================
```

It seems to be looking for geos 3.5.0 instead of the installed version, perhaps due to it having installed  libgdal v2.1.0-0 from defaults instead of libgdal v2.2.0-0 from conda-forge. Any ideas?

**Comment by ocefpaf** [comment]
@gboeing it is always annoying when the channel preference fails like that. You should not get `libgdal` from `defaults` with that configuration!

BTW, note that we changed to `libgdal`+`gdal` this week, see https://github.com/conda-forge/staged-recipes/pull/3143 for the details. I am investigating why that is happening :unamused: 

Pinging @msarahan.

**Comment by ocefpaf** [comment]
@gboeing https://github.com/gboeing/osmnx/pull/64 should help us understand what is going on.

Note that the problem was probably because not all packages (`libgdal`, `gdal`, and their dependencies compiled with `numpy 1.13`) were available yet when that test ran. This means that maybe things are just "fixed" now. However, conda should not revert to another channel in order to satisfy the packages dependencies like that. I'd rather get an error like "unable to satisfy the dependencies" than an inconsistent env.

**Comment by gboeing** [comment]
Looks like things are indeed fixed now. Thanks.

**Comment by jgerardsimcock** [comment]
I have created a new env and set conda-forge as my preferred channel. After installing geopandas, I am getting this error. pinning geos to 3.5.0 solved this problem.
