### ISSUE TITLE
Split into libgdal and gdal

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/gdal-feedstock#95]
I am not a big fan of this move, but `defaults` did this and packages on `defaults` that depend on `libgdal` get confused when mixing with `conda-forge`'s packages.

@pelson, @msarahan, @ccordoba12, @groutr, @gillins, and @kmuehlbauer what do you think? Should I just go ahead and do the split+rename here? I am on the fence, which means that I will do this if I get 3 :+1:  here :smile: 

xref: https://github.com/conda-forge/rasterio-feedstock/pull/13#issuecomment-233355130

**Comment by ccordoba12** [comment]
I don't know who's the current maintainer of Gdal in Continuum, but I'd prefer to use `gdal` and `python-gdal` instead of the current split.

Just my 2 cents ;-)

**Comment by ocefpaf** [comment]
> but I'd prefer to use `gdal` and `python-gdal` instead of the current split.

Me too BTW. (If renaming the package on `defaults` is a possibility.)

**Comment by kmuehlbauer** [comment]
For the sake of clarity `python-gdal` should be used for the python bindings. There are other bindings, which possibly find their way into conda-forge.

What are the consequences of doing the split of `gdal` (libgdal + python bindings) to `gdal` (lib only) and `python-gdal` (python bindings)?

The only real consequence would be for `conda-forge` users to have `conda install python-gdal` in the future, instead of `conda install gdal`. Or do I miss some conda-magic, which doesn't like `default`-gdal being lib+python-bindings and `conda-forge`-gdal being lib-only.

**Comment by ocefpaf** [comment]
> For the sake of clarity `python-gdal` should be used for the python bindings. There are other bindings, which possibly find their way into conda-forge.

Correct.

> What are the consequences of doing the split of `gdal` (libgdal + python bindings) to `gdal` (lib only) and `python-gdal` (python bindings)?

`gdal` is not lib only BTW. The binaries will be there. (Not even sure if we already have other bindings there.)

> The only real consequence would be for `conda-forge` users to have `conda install python-gdal` in the future, instead of `conda install gdal`. Or do I miss some conda-magic, which doesn't like `default`-gdal being lib+python-bindings and `conda-forge`-gdal being lib-only.

Yes. To be completely honest: even though I like the idea of renaming I don't like the idea of breaking people envs. Maybe it is still early and `conda-forge` can do this break without much damage. Let's see.

**Comment by dharhas** [comment]
In my opinion gdal is horribly broken already, installing gdal has been a crapshoot in terms of whether it works over time so I think renaming is fair game if it means we can have reliable installs.

**Comment by ocefpaf** [comment]
> In my opinion gdal is horribly broken already, installing gdal has been a crapshoot in terms of whether it works over time so I think renaming is fair game if it means we can have reliable installs.

But what name do you prefer? :smile: 

Note that we can only rename to `gdal` and `python-gdal` if `defatuls` follow. Otherwise we will be stuck with `libgdal` and `gdal`.

**Comment by dharhas** [comment]
I'm firmly on the side of 'practicality beats purity', I prefer 'gdal/python-gdal' but if 'libgdal/gdal' will make the pain go away I'm fine with it. 

I guess boils down to whether there is anyone we can contact on the continuum side who is able and *willing* to make the change.

**Comment by ccordoba12** [comment]
Pinging @mingwandroid about this one

**Comment by dharhas** [comment]
any idea on timeline on a decision and if there is any cross platform working combination of gdal/rasterio/fiona that is installable in the meantime. I've tried pinning to the last version before conda-forge came along and various other combinations but haven't found anything that seems to work,

**Comment by ocefpaf** [comment]
I will bring this up in our meeting, but I believe that we will have to use `libgdal` and `gdal`.

**Comment by ocefpaf** [comment]
@ccordoba12, @dharhas, and @conda-forge/gdal I am convinced we won't be able to use a different name than `defaults`.

I am also not sure that using the same name split as `defaults` will help us get some consistency as it will work only if everything is properly pinned and a version of all the packages that depends on "`libgdal`" exists in conda-forge compiled against the latest version.

However, if we do the latter correctly, we don't need to split as the dependencies will be properly handled.

I am closing this and we can re-visit it in the future if the situation changes. I am tracking cases like https://github.com/conda-forge/rasterio-feedstock/pull/13#issuecomment-233362291 and updating the packages in `conda-forge` to solve this.

**Comment by ChrisBarker-NOAA** [comment]
Sorry to re-open an old wound, but this is still a freakin' nightmare, and it seems this issue was closed with a semi-resolution that has not been followed:

"I am convinced we won't be able to use a different name than defaults."

And yet the latest "gdal" from conda-forge is the whole pile, python bindings and all. while defaults still has a "gdal" that is just the python bindings. this is ugly, as you can install libgdal from defaults (maybe accidentally), and gdal from conda-forge, and they have different versions of the same file -- but conda does not know that.

personally, I think defaults blew it -- they should have split it into "py-gdal" and "libgdal", and not re-used the gdal name.

But conda-forge has now made that worse by also re-using the gdal name.

So what should be done now? conda-forge could go its own way, and create a python-gdal package that either has the whole thing, or depends on libgdal. But having packages with the same name that mean different things on defaults and conda-forge is really, really ugly!

Do we know what defaults' plan is? If it is going to go back to a all-in-one gdal (or stop upgrading and let conda-forge handle it) then we can just wait for things to settle down. But if defaults is going to maintain a "gdal" and "libgdal" as it stands, conda-forge needs to do the same, or use a new name.

**Comment by dharhas** [comment]
So I spoke to Ilan at AnacondaCon as week or so ago. From his point of view, the reason for the split into libgdal and gdal in default is for speed of testing and building on the CI side of things. i.e. 'libgdal' takes forever to build and test. Then the python bindings 'gdal' can be built and tested really quickly for the matrix of various supported versions of python i.e. 2.7, 3.3, 3.4, 3.5, 3.6 etc. So that isn't going to change. I forgot to ask whether they were planning to continue to maintain the defaults package but I would assume they are.

**Comment by ChrisBarker-NOAA** [comment]
So I spoke to Ilan at AnacondaCon as week or so ago. From his point of
view, the reason for the split into libgdal and gdal in default is for
speed of testing and building on the CI side of things. i.e. 'libgdal'
takes forever to build and test. Then the python bindings 'gdal' can be
built and tested really quickly for the matrix of various supported
versions of python i.e. 2.7, 3.3, 3.4, 3.5, 3.6 etc.

Makes sense to me. And I generally prefer the lib to be separate from the
bindings anyway. While having a lib developer also develop python bindings
is great, having them build together has actually been a real pain for
years.

Why not follow defaults in this regard?

If there is good reason, for any package, for conda-forge to restructure,
we really should use a different naming scheme:

py-gdal

Or maybe:

gdal-complete

-CHB

**Comment by ChrisBarker-NOAA** [comment]
@ocefpaf wrote:

> I am not sure gdal will be a first class citizen on defaults due to its high complexity and low demand;

Any word form continuum on this? If they can simply leave it to conda forge in the future, that would simplify all this.

> I won't do that due to lack of time and I don't really think it is that important, but I will review and merge it someone else does it;

fair enough -- and if we keep going with the status quo -- it should stabilize a bit. I _think_ we are recommending that folks put conda-forge before defaults, and then things should "just work", yes?

Unless there is a package with an explicit libgdal dependency -- it would end up picking up gdal (with libgdal included from CF, then libgdal maybe incompatible from defaults. Hmm -- maybe we should have duplicate packages -- "libgdal" and "gdal" that are exactly the same -- both would provide the entire pile. I imagine that could make a mess somehow, but at the moment, I can't see how -- it might just work!

Or maybe safer: "libgdal" would be the whole pile, and "gdal" would be a meta-package with nothing but a dependency on libgdal. -- thoughts?

or "libgdal" is the meta-package that only brings in gdal -- kinda backwards, but it might just work.

**Comment by mingwandroid** [comment]
> Any word form continuum on this? If they can simply leave it to conda forge in the future, that would simplify all this.

We can't leave things to `conda-forge` that we depend on since we're not binary compatible, unless I'm missing something here?

**Comment by ChrisBarker-NOAA** [comment]
If other default packages depend on gdal, then it should be well supported. At least if those are "first class citizens" anyway.

**Comment by mingwandroid** [comment]
The problem goes deeper than that. Everything that depends on anything that gdal depends on needs to be binary compatible between the two endeavours.
